#!/usr/bin/env php
<?php


$av = [ 'compose' ];
$f = $argv[ 0 ];
$avv = array_slice( $argv, 1 );
$avv = implode( ' ', $avv );

$_SERVER[ 'argv' ] = [
    $f,
    'compose',
    $avv,
];

require( __DIR__ . '/afterglow' );